---
- name: Install common tools
  ansible.builtin.package:
    name: "{{ common_developer_tools }}"
    state: present

- name: Install developer tools
  ansible.builtin.package:
    name: "{{ vars[ansible_distribution | lower() + '_developer_tools'] }}"
    state: present

- name: create symlink for bat
  when: ansible_os_family == "Debian"
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    state: link
    force: false

- name: Create .ssh dir
  ansible.builtin.file:
    path: "~{{ local_username }}/.ssh"
    state: directory
    mode: '0700'

- name: Install Docker
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: Add user to docker and vboxusers groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - vboxusers

# add user to docker group to run docker commands without sudo
# add user to vboxusers group so that user can attach usb devices to guest OS
- name: Add user to docker and vboxusers groups
  ansible.builtin.user:
    name: "{{ local_username }}"
    append: true
    groups:
      - docker
      - vboxusers
