---
- name: install developer tools
  ansible.builtin.apt:
    name: "{{ base_developer_tools }}"
    state: present

- name: Install developer fonts
  ansible.builtin.apt:
    name: "{{ developer_fonts }}"
    state: present

# Fix for bat syntax highlighting tool; Ubuntu packages it as batcat instead of just bat
- name: create symlink for bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    state: link
    force: false

- name: create .ssh dir
  ansible.builtin.file:
    path: "~{{ local_username }}/.ssh"
    state: directory
    mode: '0700'
  become: true
  become_user: "{{ local_username }}"

- name: install virtualization tools
  ansible.builtin.apt:
    name: "{{ base_virtualization_tools }}"
    state: present

- name: Install docker
  ansible.builtin.import_role:
    name: geerlingguy.docker

- name: add user to docker and vboxusers groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - vboxusers

# add user to docker group to run docker commands without sudo
# add user to vboxusers group so that user can attach usb devices to guest OS
- name: add user to docker and vboxusers groups
  ansible.builtin.user:
    name: "{{ local_username }}"
    append: true
    groups:
      - docker
      - vboxusers
