---

base_productivity_tools:
  - evince
  - libreoffice
  - libreoffice-gnome
  - libreoffice-l10n-fr
  - pandoc
  - texlive
  - texlive-lang-french
  - texlive-latex-extra

base_system_tools:
  - net-tools
  - nmap
  - speedtest-cli
...
