---
base_developer_tools:
  - bat
  - build-essential
  - colordiff
  - csvkit
  - curl
  - default-jdk
  - exa
  - filezilla
  - gcc
  - git
  - golang-go
  - jq
  - make
  - maven
  - perl
  - pylint
  - python3-cachecontrol
  - python3-pep8
  - python3-pip
  - python3-poetry
  - sshfs
  - sshpass
  - tree
  - yamllint

base_virtualization_tools:
  - virtualbox
  - virtualbox-ext-pack

developer_fonts:
  - fonts-firacode
  - fonts-jetbrains-mono
  - fonts-roboto
  - fonts-open-sans
  - fonts-powerline