---

- name: Install Firefox with apt
  become: true
  block:
    - name: Remove snap package
      community.general.snap:
        name: firefox
        state: absent

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: ppa:mozillateam/ppa

    - name: Copy repo preference
      ansible.builtin.copy:
        src: mozilla-firefox
        dest: /etc/apt/preferences.d/mozilla-firefox
        mode: "7666"

    - name: Disable automatic updates
      ansible.builtin.copy:
        src: 51unattended-upgrades-firefox 
        dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
        mode: "7666"

    - name: Install Firefox
      ansible.builtin.apt:
        name: firefox
        state: present
        update_cache: true
        