---
- name: Install Mega from remote depo
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true
  block:
    - name: Add MEGASync key
      ansible.builtin.apt_key:
        url: "https://mega.nz/linux/repo/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"

    - name: Add MEGASync repo
      ansible.builtin.apt_repository:
        repo: "deb https://mega.nz/linux/repo/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/ ./"
        state: present
        filename: megasync
    
    - name: Install MEGASync
      ansible.builtin.apt:
        name: megasync
        state: present
        update_cache: true