---

- name: Install zsh and other related packages
  ansible.builtin.apt:
    name: "{{ zsh_packages }}"
    state: present
    force_apt_get: true

- name: Change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_username }}"
    shell: /bin/zsh

- name: Install antigen
  become: true
  become_user: "{{ local_username }}"
  ansible.builtin.git:
    dest: "~{{ local_username }}/.antigen"
    repo: "{{ zsh_antigen_url }}"
    version: "{{ zsh_antigen_git_version }}"

- name: "ZSH configuration file"
  become: true
  become_user: "{{ local_username }}"
  block:
    - name: Check if .zshrc exists in user's home dir
      ansible.builtin.stat:
        path: "~{{ local_username }}/.zshrc"
      register: dotzshrc

    - name: Backup .zshrc if it exists
      ansible.builtin.copy:
        src: "~{{ local_username }}/.zshrc"
        dest: "~{{ local_username }}/.zshrc.orig"
        mode: "0775"
      when: dotzshrc.stat.exists

    - name: Copy the sample .zshrc file
      ansible.builtin.copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        force: true
        mode: "0775"
