---

- name: Install zsh shell
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_username }}"
    shell: /bin/zsh

- name: Install Antidote
  ansible.builtin.git:
    dest: "~{{ local_username }}/.antidote"
    repo: https://github.com/mattmc3/antidote.git
    depth: 1

- name: "Configure Zsh"
  block:
    - name: Check if .zshrc exists in user's home dir
      ansible.builtin.stat:
        path: "~{{ local_username }}/.zshrc"
      register: dotzshrc

    - name: Backup .zshrc if it exists
      ansible.builtin.copy:
        src: "~{{ local_username }}/.zshrc"
        dest: "~{{ local_username }}/.zshrc.bak"
        mode: "0664"
      when: dotzshrc.stat.exists

    - name: Copy .zshrc configuration file
      ansible.builtin.copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        mode: "0664"

    - name: Copy .zsh_plugins.txt file
      ansible.builtin.copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        mode: "0664"