---

- name: Mount /tmp on tmpfs
  block:
    - name: Clear the existing /tmp dir (1/5)
      ansible.builtin.shell: "/bin/rm -rf *"
      args:
        chdir: /tmp
        warn: false

    - name: Copy systemd file (2/5)
      ansible.builtin.copy:
        src: /usr/share/systemd/tmp.mount
        dest: /lib/systemd/system/tmp.mount
        remote_src: True
        mode: "0775"

    - name: Create dir /etc/systemd/system/tmp.mount.d (3/5)
      ansible.builtin.file:
        path: /etc/systemd/system/tmp.mount.d
        state: directory
        mode: "0775"

    - name: Create tmp.mount custom options file (4/5)
      ansible.builtin.copy:
        dest: /etc/systemd/system/tmp.mount.d/options.conf
        content: |
          [Mount]
          Options=mode=1777,strictatime,nosuid,nodev,size=512M

    - name: Start and enable tmp.mount on boot (5/5)
      ansible.builtin.systemd:
        name: tmp.mount
        enabled: true
        state: started
        daemon_reload: true


- name: Disable system crash reports
  ansible.builtin.lineinfile:
    dest: /etc/default/apport
    regexp: "^enabled=(0|1)"
    line: enabled=0
    state: present

# It may be desirable to set this to zero, so that application memory is retained as long as possible at the expense
# of the page cache. When there is still a memory shortage, the kernel can still use swapping.
- name: Tune system swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Reduce space used by journald
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse=$'
    line: SystemMaxUse=256M

- name: Perform a dist upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Install productivity tools
  ansible.builtin.apt:
    name: "{{ base_productivity_tools }}"
    state: present
    force_apt_get: true

- name: Install system tools
  ansible.builtin.apt:
    name: "{{ base_system_tools }}"
    state: present
    force_apt_get: true
