---
- name: Reduce space used by journald
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse=$'
    line: SystemMaxUse=256M

- name: Ubuntu system setup
  when: ansible_distribution == "Ubuntu"
  block:
  - name: Disable system crash reports
    ansible.builtin.lineinfile:
      dest: /etc/default/apport
      regexp: "^enabled=(0|1)"
      line: enabled=0
      state: present

  - name: Perform a dist upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
      force_apt_get: true

  - name: Install Flatpak
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - flatpak
      - gnome-software-plugin-flatpak


- name: Fedora system setup
  when: ansible_distribution == "Fedora"
  block:
  - name: Disable system crash reports
    ansible.builtin.dnf:
      name: abrt
      state: absent

  - name: Add RPM Fusion repository
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
      disable_gpg_check: true
    loop:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"

  - name: Perform a dist upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
