---

- name: Disable system crash reports
  ansible.builtin.lineinfile:
    dest: /etc/default/apport
    regexp: "^enabled=(0|1)"
    line: enabled=0
    state: present

# It may be desirable to set this to zero, so that application memory is retained as long as possible at the expense
# of the page cache. When there is still a memory shortage, the kernel can still use swapping.
- name: Tune system swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Reduce space used by journald
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse=$'
    line: SystemMaxUse=256M

- name: Perform a dist upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Install system tools
  ansible.builtin.apt:
    name: "{{ base_system_tools }}"
    state: present

- name: Install GNOME apps
  ansible.builtin.apt:
    name: "{{ gnome_apps }}"
    state: present

- name: Install productivity tools
  ansible.builtin.apt:
    name: "{{ base_productivity_tools }}"
    state: present
